#!/usr/bin/env node
/* ============================================================
 *  build-posts.js — 把 posts/*.md 打包成 js/posts.js
 *
 *  用法：  node build-posts.js
 *
 *  每篇文章是 posts/ 下一个独立 .md 文件，互不干扰。
 *  编辑 / 新增 .md 后，重新运行本脚本即可刷新网站数据（离线可用）。
 *
 *  Frontmatter 字段（YAML 子集，够用即可）：
 *    title   (必填)  文章标题
 *    slug    (可选)  URL 用的 id，缺省取文件名（去掉 YYYY-MM-DD- 前缀）
 *    date    (必填)  发布日期 YYYY-MM-DD，决定列表排序（新→旧）
 *    tags    (可选)  [标签1, 标签2]   或下方用「- 标签」块列表
 *    summary (必填)  列表页摘要
 *    cover   (可选)  CSS 背景值，如 linear-gradient(135deg,#5EEAD4,#A78BFA)
 *    draft   (可选)  true 则跳过该篇
 * ============================================================ */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const POSTS_DIR = path.join(ROOT, "posts");
const OUT_FILE = path.join(ROOT, "js", "posts.js");
const DEFAULT_COVER = "linear-gradient(135deg,#5EEAD4,#A78BFA)";

function parseScalar(s) {
  s = String(s).trim();
  if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))) {
    return s.slice(1, -1);
  }
  if (s === "true") return true;
  if (s === "false") return false;
  return s;
}

function parseFrontmatter(text) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!m) return { data: null, body: text };
  const fm = m[1];
  const body = text.slice(m[0].length).replace(/^\r?\n/, "");
  const data = {};
  let key = null;
  for (const raw of fm.split(/\r?\n/)) {
    if (raw.trim() === "") continue;
    const li = raw.match(/^\s*-\s+(.*)$/);
    if (li && key) {
      if (!Array.isArray(data[key])) data[key] = [];
      data[key].push(parseScalar(li[1]));
      continue;
    }
    const kv = raw.match(/^([A-Za-z0-9_]+):\s*(.*)$/);
    if (kv) {
      key = kv[1];
      const val = kv[2];
      const arr = val.match(/^\[(.*)\]$/);
      if (arr) {
        const inner = arr[1].trim();
        data[key] = inner === "" ? [] : inner.split(",").map((x) => parseScalar(x));
        key = null;
      } else if (val.trim() === "") {
        data[key] = [];
      } else {
        data[key] = parseScalar(val);
        key = null;
      }
    }
  }
  return { data, body };
}

function deriveSlug(filename) {
  const base = filename.replace(/\.md$/i, "");
  const m = base.match(/^\d{4}-\d{2}-\d{2}-(.+)$/);
  return m ? m[1] : base;
}

function dateFromName(filename) {
  const m = filename.match(/^(\d{4}-\d{2}-\d{2})/);
  return m ? m[1] : "";
}

function build() {
  if (!fs.existsSync(POSTS_DIR)) {
    console.error("未找到 posts/ 目录：", POSTS_DIR);
    process.exit(1);
  }
  const files = fs.readdirSync(POSTS_DIR).filter((f) => f.toLowerCase().endsWith(".md")).sort();
  const posts = [];
  let skipped = 0;

  for (const f of files) {
    const full = path.join(POSTS_DIR, f);
    const { data, body } = parseFrontmatter(fs.readFileSync(full, "utf8"));

    if (!data) {
      // 没有 frontmatter：整篇当作正文
      const slug = deriveSlug(f);
      posts.push({
        id: slug,
        title: (body.match(/^#\s+(.+)$/m) || [, slug])[1] || slug,
        date: dateFromName(f),
        tags: [],
        summary: "",
        cover: DEFAULT_COVER,
        markdown: body,
      });
      continue;
    }
    if (data.draft === true) { skipped++; continue; }

    posts.push({
      id: String(data.slug || deriveSlug(f)),
      title: data.title || deriveSlug(f),
      date: data.date || dateFromName(f),
      tags: Array.isArray(data.tags) ? data.tags : [],
      summary: data.summary || "",
      cover: data.cover || DEFAULT_COVER,
      markdown: body,
    });
  }

  posts.sort((a, b) => String(b.date).localeCompare(String(a.date)));

  const header =
    "/* AUTO-GENERATED by build-posts.js — 请勿手改。\n" +
    " * 新增 / 编辑文章请改 posts/*.md，然后运行：node build-posts.js\n" +
    " */\n";
  const out = header + "window.POSTS = " + JSON.stringify(posts, null, 2) + ";\n";
  fs.writeFileSync(OUT_FILE, out, "utf8");

  console.log("✓ 已生成 js/posts.js");
  console.log("  文章数：" + posts.length + (skipped ? "（跳过草稿 " + skipped + " 篇）" : ""));
  console.log("  源文件：" + (files.length ? files.join("、") : "（无）"));
}

build();
